### ISSUE TITLE
Can't figure out how to disable the !switch command

### ISSUE THREAD

**Issue by DinnerBug** [F1F7Y/ServerUtilities#19]
It doesn't seem to be a convar... how would I disable it?

**Comment by F1F7Y** [comment]
There is no way to disable `!switch`. The only way you could achieve this is by disabling/deleting `Fifty.ServerTeamBalance` mod

**Comment by DinnerBug** [comment]
I had FSTB_TEAM_BALANCE_ENABLED 0 already in my config and the server still let me use the !switch command

**Comment by F1F7Y** [comment]
My bad, I meant disabling the mod in northstar so it's not loaded at all.

**Comment by DinnerBug** [comment]
That did the trick, cheers very much
